"""Shared values and the registry; the standard library and PyTorch only."""

from __future__ import annotations

from src.core.entities import (
    CELLS,
    ERROR,
    OVERLAP,
    SEGMENT,
    Bars,
    Batch,
    ClassDistribution,
    DatasetInfo,
    DatasetStatistics,
    Distribution,
    InputInfo,
    LossOutput,
    Matrix,
    ModelOutput,
    Normalization,
    Sample,
    StepOutput,
    TargetInfo,
    ValueDistribution,
    as_children,
    class_name,
    submodule_at,
    validate_classes,
    validate_name,
)
from src.core.registry import Registry
from src.core.taxonomy import (
    SPATIAL,
    Axis,
    Geometry,
    Modality,
    Representation,
    Role,
    Semantics,
    Stage,
    Stream,
)
from src.core.types import (
    FEATURE_AXIS,
    ShapeTree,
    TensorShape,
    TensorTree,
    drop_feature_axis,
    require_tensor,
)

__all__ = [
    "CELLS",
    "ERROR",
    "FEATURE_AXIS",
    "OVERLAP",
    "SEGMENT",
    "SPATIAL",
    "Axis",
    "Bars",
    "Batch",
    "ClassDistribution",
    "DatasetInfo",
    "DatasetStatistics",
    "Distribution",
    "Geometry",
    "InputInfo",
    "LossOutput",
    "Matrix",
    "Modality",
    "ModelOutput",
    "Normalization",
    "Registry",
    "Representation",
    "Role",
    "Sample",
    "Semantics",
    "ShapeTree",
    "Stage",
    "StepOutput",
    "Stream",
    "TargetInfo",
    "TensorShape",
    "TensorTree",
    "ValueDistribution",
    "as_children",
    "class_name",
    "drop_feature_axis",
    "require_tensor",
    "submodule_at",
    "validate_classes",
    "validate_name",
]
